name: Pytest

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: "x64"
  
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Test Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      # Run Unit Tests
      - name: Test with pytest
        run: python -m pytest --import-mode=append tests/unit/

